---
# vars file for loki-deploy
loki_version: 3.3.2
loki_platform: linux-amd64
loki_archive: "loki-{{ loki_platform }}.zip"
gh_release_page: https://github.com/grafana/loki/releases/download
loki_download_link: "{{ gh_release_page }}/v{{ loki_version }}/loki-{{ loki_platform }}.zip"
