- name: Install Grafana on the system
  hosts: localhost
  tasks: 
  # TODO(os detection): Handle cases where systems are of the RedHat family
  # (ansible_os_family). ansible.builtin.package detects the native package manager.
  # Can't use it to add repos tho

  ######################### Debian-based Systems #############################
    - name: Download Grafana GPG key for Debian based systems
      ansible.builtin.get_url:
        url: https://apt.grafana.com/gpg.key 
        dest: /usr/share/keyrings/grafana.key
        mode: '0644'
      when: ansible_os_family == "Debian"

    - name: Add Grafana apt repository on Debian based systems
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/grafana.list
        content: |
          deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main
        mode: '0644'
      when: ansible_os_family == "Debian"

        # # TODO: Move to ansible.builtin.lineinfile
    # - name: Add the Grafana apt repository on Debian based systems
      # become: yes
      # ansible.builtin.shell:
        # cmd: |
        #   echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
      # when: ansible_os_family == "Debian"

    - name: Install Grafana and dependencies on Debian based systems
      become: yes
      ansible.builtin.apt:
        name: 
          - apt-transport-https
          - software-properties-common
          - unzip
          - grafana-enterprise
        state: present
        update_cache: yes
      notify: Start Grafana
      when: ansible_os_family == "Debian"

      ########################## RedHat based Systems #########################
      # To comply with the "must work in ProLUG environment" requirement

    - name: Download the GPG key on RedHat based systems
      become: yes
      ansible.builtin.get_url:
        url: https://rpm.grafana.com/gpg.key
        dest: /etc/pki/rpm-gpg/RPM_GPG_KEY_grafana
        mode: '0644'
      when: ansible_os_family == "RedHat"

    - name: Add the Grafana yum repository for RedHat based Systems
      become: yes
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/grafana.repo
        content: |
          [grafana]
          name=Grafana Server
          baseurl=https://rpm.grafana.com
          repo_gpgcheck=1
          enabled=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM_GPG_KEY_grafana
        mode: '0644'
      when: ansible_os_family == "RedHat"

    - name: Install Grafana and Dependencies on RedHat based systems
      become: yes
      ansible.builtin.package:  # In case of older systems without dnf
        name: 
          - dnf-plugins-core
          - unzip
          - grafana-enterprise
        state: present
      when: ansible_os_family == "RedHat"
      notify: 
        - Start Grafana

    - name: Open Firewalld port 3000 
      become: yes
      ansible.builtin.shell:
        cmd: |
          firewall-cmd --add-port=3000/tcp --permanent 
          firewall-cmd --reload
      when: ansible_os_family == "RedHat"

      ##################### end RH compliance ########################

    - name: Save host IP
      ansible.builtin.shell:
        cmd: "hostname -I | awk '{ print $1 }'"
      register: grafana_host_ip
      notify: Generate Grafana link


  handlers:
    - name: Start Grafana
      become: yes
      ansible.builtin.systemd:
        daemon_reload: true
        name: grafana-server
        state: started
        enabled: true

    - name: Generate Grafana link
      ansible.builtin.debug:
        msg: "Grafana link: http://{{ grafana_host_ip.stdout | trim }}:3000"

      
