- name: Install Grafana on the system
  hosts: localhost
  tasks: 

    - name: Download Grafana GPG key
      ansible.builtin.get_url:
        url: https://apt.grafana.com/gpg.key 
        dest: /usr/share/keyrings/grafana.key
        mode: '0644'

    - name: Add the Grafana apt repository
      become: yes
      ansible.builtin.shell:
        cmd: |
          echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

    - name: Install Grafana and dependencies
      become: yes
      ansible.builtin.apt:
        name: 
          - apt-transport-https
          - software-properties-common
          - unzip
          - grafana-enterprise
        state: present
        update_cache: yes
      notify: Start Grafana

    - name: Save host IP
      ansible.builtin.shell:
        cmd: "hostname -I | awk '{ print $1 }'"
      register: grafana_host_ip
      notify: Generate Grafana link


  handlers:
    - name: Start Grafana
      become: yes
      ansible.builtin.systemd:
        daemon_reload: true
        name: grafana-server
        state: started
        enabled: true

    - name: Generate Grafana link
      ansible.builtin.debug:
        msg: "Grafana link: http://{{ grafana_host_ip.stdout | trim }}:3000"

