- name: Set up prometheus
  hosts: localhost  # Placeholder
  tasks:
    - name: Create a user account for Prometheus
      ansible.builtin.user:
        name: prometheus

    - name: Create the /var/lib/prometheus directory
      ansible.builtin.file:
        path: /var/lib/prometheus
        state: directory
        mode: '0755'

    - name: Download and extract Prometheus and its dependencies
      become: yes
      ansible.builtin.shell:
        cmd: |
          curl -o /tmp/prometheus-3.0.1.linux-amd64.tar.gz https://github.com/prometheus/prometheus/releases/download/v3.0.1/prometheus-3.0.1.linux-amd64.tar.gz
          tar -xzf /tmp/prometheus-3.0.1.linux-amd64.tar.gz -C /var/lib/prometheus --strip-components=1
          cp /var/lib/prometheus/prometheus /usr/bin/prometheus
          chown -R prometheus:prometheus /usr/bin/prometheus

